### ISSUE TITLE
(feedback would be appreciated) Stops during the print (about 3 seconds)

### ISSUE THREAD

**Issue by T9Air** [T9Air/Klipper_Power_Resume#53]
For whatever reason, since I believe v3.2.1 or v3.2.0, after every few lines of the file, the "Klipper load" jumps up to about 90%. I do not think this is because of the macro itself, because when I run it not during a print, it executes in a very short amount of time. More research is needed.

If someone could please test v3.2.2 and report back if they have the same problem, it would be greatly appreciated.

**Comment by T9Air** [comment]
After releasing v3.2.2, i will work on this

**Comment by T9Air** [comment]
This problem did not occur before v3, so I will try it with an earlier version.

**Comment by T9Air** [comment]
3.0.0 has the bug, but I do not remember it having that before.

**Comment by T9Air** [comment]
When sending the command to LOG_FILE, it works perfectly fine and does not stop printing. However, when the LOG_FILE macro is in the print file itself it does stop printing.

**Comment by T9Air** [comment]
For now, I am just going to recommend skipping about 5 lines, I think that may just be the problem

**Comment by garethbradley** [comment]
Hey, testing this and had the same problem:
[Unexpected Pause](https://youtu.be/d7b8LHPGDlw)

**Comment by T9Air** [comment]
@garethbradley When adding the macros to the file, how many lines did you tell it to skip?

**Comment by garethbradley** [comment]
5 lines. I haven't tested any other values but it was telling that it paused on outer walls regardless of whether they were external or internal (screw holes etc.)

**Comment by T9Air** [comment]
If you skip about 10-15 lines (or more), does it still cause the error? I believe it pauses because commands are sent in batches, and when there are too many LOG_FILE commands it causes the MCU to have to wait a while until more commands are sent.

**Comment by T9Air** [comment]
I will have to test this, but I am pretty sure if I run the log.sh script as a subprocess (`~/Klipper_Power_Resume/log.sh &`), the script will run in the background, and will not cause the printer to need to wait for it to finish.

**Comment by T9Air** [comment]
Closed it by mistake
