### ISSUE TITLE
Multi Printer support

### ISSUE THREAD

**Issue by khisanthax** [T9Air/Klipper_Power_Resume#63]
**Is your feature request related to a problem? Please describe.**
I have four printers connected to klipper, as such I have four printer data directories and four instances of Klipper but the script does not recognize any directories except the default directory.

**Describe the solution you'd like**
It would be great for the script to recognize multiple klipper instances and install the files to each or give an option of which directories to install to.

**Comment by T9Air** [comment]
I am currently working on a different project, but I will try to get to work on this within a week or so.

**Comment by khisanthax** [comment]
No worries and thanks for your attention!

**Comment by T9Air** [comment]
@khisanthax Your printer_data files are named like this: printer_(printer name)_data, right?

**Comment by T9Air** [comment]
@khisanthax I would like to work on this, but I need you to answer my question so that I can help.

**Comment by khisanthax** [comment]
I'm so sorry, I didn't see this sooner.  Yes, that's correct.  printer_Ender3S1_data.

**Comment by T9Air** [comment]
@khisanthax Could you test the [feature](https://github.com/T9Air/Klipper_Power_Resume/pull/67)? I do not have multiple 3d printers, so I will need you to test it.

**Comment by khisanthax** [comment]
I would be happy to test it, I have a 16hr print going but once it's done I'll try it and let you know!

**Comment by T9Air** [comment]
> I would be happy to test it, I have a 16hr print going but once it's done I'll try it and let you know!

Enjoy the wait :)

**Comment by T9Air** [comment]
@khisanthax Does it work?

**Comment by khisanthax** [comment]
I messed up the install and had to restore the VM, I'm going to try again by tomorrow and let you know my progress.

**Comment by khisanthax** [comment]
working on it now!

**Comment by khisanthax** [comment]
okay, so I run the bash, I've installed the gcode shell, and when I press 1 to install for all the chmod it says operation not permitted.
![chrome_xz8XMfQon6](https://github.com/user-attachments/assets/18147794-3a6b-4adc-9211-fb900324d89a)

I'm running on ubuntu 22.04.  I tried sudo bash kpr.sh but it said no command found, I'm guessing I did it wrong.

**Comment by khisanthax** [comment]
I didn't realize there was a different command for the install, I'll try that again and post back.

**Comment by khisanthax** [comment]
I used the install for 3.5.0 branch and it recognized all four printers, however, I'm still having the "operation not permitted" problem.  I installed the gcode shell first and then ran you're install.  Is there something else I can try?

**Comment by khisanthax** [comment]
I did get this error when selecting a printer: https://i.imgur.com/nfPFPrC.png

**Comment by T9Air** [comment]
It should be fixed now. Run the uninstall script, then run `git pull origin v3.5.0` in the terminal, and then rerun the install script.
