### ISSUE TITLE
Better documentation on how to actually restart a print

### ISSUE THREAD

**Issue by meltiseugen** [T9Air/Klipper_Power_Resume#65]
I've been readding the docs, before i started to install your script, but it is not clear for me how to ACTUALLY restart a print.

Do I need to ssh into the rpi and re-run your script?
Do I need to add some macros to layer changes?

What are the steps to actually restart a print when power loss/klipper disconnects?
Is it possible to do this using a single macro after power loss?

One of my use cases is that I have a remote printer, where ssh-ing to the rpi is not possible, so I would like to have a simple macro that has the default values and just resumes the print.

I would really appreciate it if you could clarify these :D Thank you!

**Comment by T9Air** [comment]
Thank you for bringing that to my attention! I am not sure if your use case with the remote printer is possible currently, but I may be able to work on that at a later time.

**Comment by T9Air** [comment]
@meltiseugen Did the changes help you? Also, if you could create a feature request for your use case, and give more details, it would help me figure out how to implement it.
